application: itsaballthatrolls
version: 1
api_version: 1
runtime: python27

handlers:
- url: /scripts
  static_dir: scripts
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest